name: PHP CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the testUnitJS branch
  push:
    branches: [testUnitJS]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: "7.4"
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          extensions: mbstring, intl
          tools: prestissimo

      - name: Install dependencies
        run: cd Back && composer install

      - name: Run test
        run: php bin/phpunit
