name: PHP CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the testUnitJS branch
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: cd Back && docker-compose up -d

      - name: Drop, create and migrate tables
        run: |
          cd Back
          docker-compose exec -T app composer install
          docker-compose exec -T app php bin/console doctrine:database:drop --force --env=test || true
          docker-compose exec -T app php bin/console doctrine:database:create --env=test
          docker-compose exec -T app php bin/console doctrine:migrations:migrate -n --env=test
          docker-compose exec -T app php bin/console doctrine:fixtures:load -n --env=test
          docker-compose exec -T app php bin/phpunit
